FROM nvcr.io/nvidia/pytorch:21.03-py3

RUN pip3 install -i https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110
RUN pip3 install torchvision imgaug Pillow lmdb pytest munch pyyaml tqdm numba numpy sklearn
